version: '3.8'

services:
  pgvector:
    image: ankane/pgvector
    container_name: pgvector_demo
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vectordb
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    # 不挂载数据卷，容器销毁后数据会清除
